# GitHub Marketplace entry point

name: "GodScore CI"
description: "Survivability-aware CI gate enforcing God Variable (Gv) thresholds."
author: "William Shacklett"

branding:
  icon: "shield"
  color: "blue"

inputs:
  score:
    description: "God Variable score to evaluate."
    required: true

  threshold:
    description: "Minimum allowed Gv score."
    required: false
    default: "0.80"

  mode:
    description: "Execution mode: free (warn) or pro (fail)."
    required: false
    default: "free"

  pro_token:
    description: "Optional Pro token. Pass secrets.GV_PRO_TOKEN to enable pro enforcement."
    required: false
    default: ""

outputs:
  passed:
    description: "Whether the Gv gate passed."

runs:
  using: "composite"
  steps:
    # This ensures gv_gate.py exists even when the action is used from another repository.
    - name: Checkout GodScore CI action repo
      uses: actions/checkout@v4
      with:
        repository: willshacklett/godscore-ci
        ref: main
        path: godscore-ci

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Run GodScore Gate
      shell: bash
      env:
        GV_PRO_TOKEN: ${{ inputs.pro_token }}
      run: |
        set +e
        python godscore-ci/gv_gate.py \
          --score "${{ inputs.score }}" \
          --threshold "${{ inputs.threshold }}" \
          --mode "${{ inputs.mode }}"
        code=$?
        if [ $code -eq 0 ]; then
          echo "passed=true" >> "$GITHUB_OUTPUT"
        else
          echo "passed=false" >> "$GITHUB_OUTPUT"
        fi
        exit $code
