# GitHub Marketplace entry point

name: "GodScore CI"
description: "Survivability-aware CI gate enforcing God Variable (Gv) thresholds."
author: "William Shacklett"

branding:
  icon: "shield"
  color: "blue"

inputs:
  score:
    description: "God Variable score to evaluate."
    required: true

  threshold:
    description: "Minimum allowed Gv score."
    required: false
    default: "0.80"

  mode:
    description: "Execution mode: free (warn on regression) or pro (fail on regression)."
    required: false
    default: "free"

  pro_token:
    description: "Optional Pro token. Pass secrets.GV_PRO_TOKEN to enable pro enforcement."
    required: false
    default: ""

outputs:
  passed:
    description: "Whether the Gv gate passed."

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml

    - name: Run GodScore Gate
      shell: bash
      env:
        GV_PRO_TOKEN: ${{ inputs.pro_token }}
      run: |
        python gv_gate.py \
          --score "${{ inputs.score }}" \
          --threshold "${{ inputs.threshold }}" \
          --mode "${{ inputs.mode }}"
