name: "GodScore CI"
description: "Constraint-based governance score with memory. AutoScore v1 + GV spine. Optional enforcement."

inputs:
  score:
    description: "Optional. 0..1 or 0..100. Omit or set to 'auto' to compute AutoScore v1 -> GV -> GodScore."
    required: false
  threshold:
    description: "Minimum GodScore required. 0..1 or 0..100."
    required: false
    default: "0.80"
  mode:
    description: "free | pro"
    required: false
    default: "free"
  enforce:
    description: "true/false. In pro mode, fail if below threshold."
    required: false
    default: "false"

outputs:
  godscore:
    description: "Computed GodScore (0..1)."
  gv:
    description: "Computed GV (0..1)."
  passed:
    description: "true if score >= threshold."
  effective_mode:
    description: "free or pro."
  score_source:
    description: "manual or auto."

runs:
  using: "composite"
  steps:
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: "Install dependencies"
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f pyproject.toml ]; then pip install .; fi

    - name: "Run GodScore CI"
      shell: bash
      run: |
        python -m godscore_ci.action_main
